name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  Build:
    name: Publish Serverless Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          ref: vercel
          path: out
      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build code for Vercel
        run: yarn vercel-build
      - name: Push new code
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo -e "\n# Remove any old files in the dist folder"
          rm -rfv out/api/*

          echo -e "\n# Move the generated docs to the newly-checked-out repo, to be committed and pushed"
          rsync -vaI api/ out/api

          echo -e "\n# Commit and push"
          cd out
          git add --all .
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "build: vercel build for ${GITHUB_SHA}" || true
          git push origin vercel
