name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    name: Linting
    uses: sapphiredev/.github/.github/workflows/reusable-lint.yml@main

  building:
    name: Building
    uses: sapphiredev/.github/.github/workflows/reusable-build.yml@main
